[package]
name = "my-crate"
version = "0.1.0"
edition = "2021"

[dependencies]
type-one = { path = "../type-one" }
requires-serialize = { path = "../requires-serialize" }
compat = { path = "../compat" }
